#!/usr/bin/env python
# Generated by jaraco.develop (https://bitbucket.org/jaraco/jaraco.develop)
from setuptools import find_packages
setup_params = dict(
	name='jaraco.institutions',
	use_hg_version=True,
	packages=find_packages(),
	namespace_packages=['jaraco'],
	zip_safe=False,
	entry_points = dict(
		financial_institutions = [
			'Los Alamos National Bank=jaraco.institutions.sites:LANB',
			'Chase (Credit Card)=jaraco.institutions.sites:Chase',
			'SLFCU=jaraco.institutions.sites:SLFCU',
			'Fidelity=jaraco.institutions.sites:Fidelity',
		],
	),
	setup_requires=[
		'hgtools',
	],
)
if __name__ == '__main__':
	from setuptools import setup
	setup(**setup_params)
